parameters:
    cisco.filter.config:
        example:
            exportable: false
            persistent: false
            filters:
                aYearFilter:
                    type: year
                    accesslevel: 1
                aMonthFilter:
                    type: month
                    accesslevel: 1
                aCustomFilter:
                    type: custom
                    accesslevel: 1
