parameters:
    cisco.filter.config:
        example:
            exportable: false
            persistent: false
            filters:
                aYearFilter:
                    type: year
                    access_control:
                        role:
                            show: [ ROLE_ADMIN ]
                            enable: [ ROLE_ADMIN ]
                aMonthFilter:
                    type: month
                aCustomFilter:
                    type: custom
