parameters:
    cisco.filter_service.class: CiscoSystems\FilterBundle\FilterService
    cisco.filter.custom.class: CiscoSystems\FilterBundle\Filter\CustomFilter
    cisco.filter.year.class: CiscoSystems\FilterBundle\Filter\YearFilter
    cisco.filter.month.class: CiscoSystems\FilterBundle\Filter\MonthFilter
    cisco.twig.filter_extension.class: CiscoSystems\FilterBundle\Twig\Extension\FilterExtension
    cisco.filter_access.role.class: CiscoSystems\FilterBundle\Access\FilterAccessRole

services:
    # main service
    cisco.filter:
        class: '%cisco.filter_service.class%'
        arguments:
            - '%cisco.filter.config%'
        calls:
            - [ setContainer, [ '@service_container' ]]
    # some default filter types
    cisco.filter.custom:
        class: '%cisco.filter.custom.class%'
        tags:
          - { name: cisco.filter.filtertype, alias: custom }
    cisco.filter.year:
        class: '%cisco.filter.year.class%'
        tags:
          - { name: cisco.filter.filtertype, alias: year }
    cisco.filter.month:
        class: '%cisco.filter.month.class%'
        tags:
          - { name: cisco.filter.filtertype, alias: month }
    # Twig extension
    cisco.twig.filter.extension:
        class: '%cisco.twig.filter_extension.class%'
        arguments:
            - '@cisco.filter'
            - '@twig'
        tags:
            - { name: twig.extension }
    # some default access control
    cisco.filter_access.role:
        class: '%cisco.filter_access.role.class%'
        arguments:
            - '@security.context'
        tags:
          - { name: cisco.filter.filteraccess, alias: role }